### ISSUE TITLE
Build error  'sqlite3.c' file not found

### ISSUE THREAD

**Issue by TThana** [brody2consult/Android-sqlite-native-driver-regexp-pcre#1]
thanas-mac-mini:sqlite2 thana$ make
rm -rf lib libs
ndk-build
Android NDK: APP_PLATFORM not set. Defaulting to minimum supported version android-16.    
make[1]: Entering directory `/Users/thana/Desktop/sqlite2'
[armeabi-v7a] Compile thumb  : sqlc-native-driver <= sqlc_all.c
jni/../native/sqlc_all.c:4:10: fatal error: 'sqlite3.c' file not found
#include "sqlite3.c"
         ^~~~~~~~~~~
1 error generated.
make[1]: *** [obj/local/armeabi-v7a/objs/sqlc-native-driver/__/native/sqlc_all.o] Error 1
make[1]: Leaving directory `/Users/thana/Desktop/sqlite2'
make: *** [ndkbuild] Error 2
thanas-mac-mini:sqlite2 thana$

**Comment by brody2consult** [comment]
FYI this native-driver version is no longer supported. I would *highly* recommend building from <https://github.com/brodybits/Android-sqlite-ext-native-driver>, which supports REGEXP using builtin `regex.h`, has SQLite 3.26.0 (still needs SQLite 3.28.0 update), and should be more consistent with iOS platform.

P.S. In case anyone else finds this issue, this error is resolved by doing `make init` before `make`. I have seen others make the same mistake in the past.

**Comment by TThana** [comment]
thank you for the suggestion
